use std::fmt::Write as _;

use haphe::{
    BackendCapabilities, BindingGenerator, ConstantDescriptor, EnumDescriptor,
    ForeignInterfaceDescriptor, FunctionDescriptor, GeneratedFile, GeneratedOutput,
    ModuleDescriptor, PrimitiveType, StructDescriptor, TypeAliasDescriptor, TypeDescriptor,
    ValidatedRegistry, VariantKind,
};

use crate::RhaiBinder;
pub use crate::error::RhaiDeclError;

#[derive(Debug, Clone)]
pub struct RhaiDeclGenerator {
    path: String,
}

impl RhaiDeclGenerator {
    pub fn new() -> Self {
        Self {
            path: "definitions.d.rhai".to_string(),
        }
    }

    pub fn with_path(mut self, path: impl Into<String>) -> Self {
        self.path = path.into();
        self
    }
}

impl Default for RhaiDeclGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl BindingGenerator for RhaiDeclGenerator {
    type Error = RhaiDeclError;

    fn language_name(&self) -> &'static str {
        "rhai"
    }

    fn capabilities(&self) -> BackendCapabilities {
        RhaiBinder::default_capabilities()
    }

    fn generate(&self, registry: &ValidatedRegistry<'_>) -> Result<GeneratedOutput, Self::Error> {
        let mut out = String::from("// haphe definitions for Rhai\n// Generated by haphe-rhai\n\n");
        check_unique_type_names(registry)?;

        for s in registry.structs() {
            emit_struct(&mut out, s);
        }
        for e in registry.enums() {
            emit_enum(&mut out, e);
        }
        for a in registry.type_aliases() {
            emit_alias(&mut out, a);
        }
        for fi in registry.foreign_interfaces() {
            emit_foreign(&mut out, fi);
        }
        for module in registry.modules() {
            emit_module(&mut out, registry, module, 0);
        }

        Ok(GeneratedOutput {
            files: vec![GeneratedFile {
                path: self.path.clone(),
                content: out.into_bytes(),
                encoding: Some("utf-8".to_string()),
            }],
        })
    }
}

fn check_unique_type_names(registry: &ValidatedRegistry<'_>) -> Result<(), RhaiDeclError> {
    let mut names: Vec<&str> = Vec::new();
    let all = registry
        .structs()
        .iter()
        .map(|s| s.name)
        .chain(registry.enums().iter().map(|e| e.name))
        .chain(registry.type_aliases().iter().map(|a| a.name))
        .chain(registry.foreign_interfaces().iter().map(|f| f.name));
    for name in all {
        if names.contains(&name) {
            return Err(RhaiDeclError::DuplicateTypeName {
                name: name.to_string(),
            });
        }
        names.push(name);
    }
    Ok(())
}

fn indent(out: &mut String, depth: usize) {
    for _ in 0..depth {
        out.push_str("  ");
    }
}

fn emit_doc(out: &mut String, doc: Option<&str>, depth: usize) {
    if let Some(doc) = doc {
        for line in doc.lines() {
            indent(out, depth);
            let _ = writeln!(out, "// {line}");
        }
    }
}

fn emit_struct(out: &mut String, s: &StructDescriptor<'_>) {
    emit_doc(out, s.doc, 0);
    let _ = writeln!(out, "// === Type: {} ===", s.name);

    if !s.fields.is_empty() {
        let _ = writeln!(out, "// Fields:");
        for field in s.fields {
            let ty = render_type(field.ty);
            let ro = if field.readonly { "  (readonly)" } else { "" };
            let _ = writeln!(out, "//   {}: {ty}{ro}", field.name);
        }
    }

    if !s.properties.is_empty() {
        let _ = writeln!(out, "// Properties:");
        for prop in s.properties {
            let ty = render_type(prop.ty);
            let ro = if prop.readonly { "  (readonly)" } else { "" };
            let _ = writeln!(out, "//   {}: {ty}{ro}", prop.name);
        }
    }

    let instance_methods: Vec<_> = s
        .methods
        .iter()
        .filter(|m| m.receiver.is_some())
        .collect();
    if !instance_methods.is_empty() {
        let _ = writeln!(out, "// Methods:");
        for m in &instance_methods {
            emit_fn_signature(out, m, "//   ");
        }
    }

    if !s.constructors.is_empty() {
        let _ = writeln!(out, "// Constructors:");
        for c in s.constructors {
            emit_fn_signature_with_ret(out, c, s.name, "//   ");
        }
    }

    let associated_fns: Vec<_> = s
        .methods
        .iter()
        .filter(|m| m.receiver.is_none())
        .collect();
    if !associated_fns.is_empty() {
        let _ = writeln!(out, "// Associated functions:");
        for a in &associated_fns {
            emit_fn_signature(out, a, "//   ");
        }
    }

    let ops = collect_operators(s.trait_impls);
    if !ops.is_empty() {
        let _ = writeln!(out, "// Operators: {}", ops.join(", "));
    }

    let _ = writeln!(out);
}

fn emit_enum(out: &mut String, e: &EnumDescriptor<'_>) {
    emit_doc(out, e.doc, 0);
    let _ = writeln!(out, "// === Enum: {} ===", e.name);

    let unit_cases: Vec<_> = e
        .variants
        .iter()
        .filter(|v| matches!(v.kind, VariantKind::Unit))
        .collect();
    let payload_cases: Vec<_> = e
        .variants
        .iter()
        .filter(|v| !matches!(v.kind, VariantKind::Unit))
        .collect();

    if !unit_cases.is_empty() {
        let names: Vec<&str> = unit_cases.iter().map(|v| v.name).collect();
        let _ = writeln!(out, "// Cases: {}", names.join(", "));
    }
    for v in &payload_cases {
        let fields = match &v.kind {
            VariantKind::Tuple(tys) => tys.iter().map(|t| render_type(t)).collect::<Vec<_>>(),
            VariantKind::Struct(fs) => fs
                .iter()
                .map(|f| format!("{}: {}", f.name, render_type(f.ty)))
                .collect(),
            VariantKind::Unit => unreachable!(),
        };
        let _ = writeln!(out, "// Case {}({})", v.name, fields.join(", "));
    }

    if !e.methods.is_empty() {
        let _ = writeln!(out, "// Methods:");
        for m in e.methods {
            emit_fn_signature(out, m, "//   ");
        }
    }

    let _ = writeln!(out);
}

fn emit_alias(out: &mut String, a: &TypeAliasDescriptor<'_>) {
    emit_doc(out, a.doc, 0);
    let inner = render_type(a.inner);
    let transparent = if a.transparent { " (transparent)" } else { "" };
    let _ = writeln!(out, "// === Alias: {} = {inner}{transparent} ===\n", a.name);
}

fn emit_foreign(out: &mut String, fi: &ForeignInterfaceDescriptor<'_>) {
    emit_doc(out, fi.doc, 0);
    let _ = writeln!(out, "// === Foreign: {} ===", fi.name);
    let _ = writeln!(out, "// Callbacks map:");
    for f in fi.functions {
        emit_fn_signature(out, f, "//   ");
    }
    let _ = writeln!(out);
}

fn emit_module(
    out: &mut String,
    registry: &ValidatedRegistry<'_>,
    module: &ModuleDescriptor<'_>,
    depth: usize,
) {
    indent(out, depth);
    let _ = writeln!(out, "// === Module: {} ===", module.name);

    if !module.constants.is_empty() {
        indent(out, depth);
        let _ = writeln!(out, "// Constants:");
        for constant in module.constants {
            emit_constant(out, constant, depth + 1);
        }
    }

    if !module.type_ids.is_empty() {
        let type_names: Vec<&str> = module
            .type_ids
            .iter()
            .filter_map(|id| {
                registry.get_type(id).map(|tk| match tk {
                    haphe::TypeKind::Struct(s) => s.name,
                    haphe::TypeKind::Enum(e) => e.name,
                    haphe::TypeKind::TypeAlias(a) => a.name,
                })
            })
            .collect();
        if !type_names.is_empty() {
            indent(out, depth);
            let _ = writeln!(out, "// Types: {}", type_names.join(", "));
        }
    }

    if !module.functions.is_empty() {
        indent(out, depth);
        let _ = writeln!(out, "// Functions:");
        for f in module.functions {
            indent(out, depth + 1);
            emit_fn_signature(out, f, "// ");
        }
    }

    for submodule in module.submodules {
        emit_module(out, registry, submodule, depth + 1);
    }

    if depth == 0 {
        let _ = writeln!(out);
    }
}

fn emit_constant(out: &mut String, c: &ConstantDescriptor<'_>, depth: usize) {
    indent(out, depth);
    let ty = render_type(c.ty);
    let _ = writeln!(out, "// {}: {ty} = {}", c.name, c.value);
}

fn emit_fn_signature(out: &mut String, f: &FunctionDescriptor<'_>, prefix: &str) {
    if !f.generic_params.is_empty() && f.dispatch != haphe::Dispatch::Dyn {
        for inst in f.instantiations {
            let mangled = crate::binder::mangle_generic_name(f.name, inst);
            let _ = write!(out, "{prefix}fn {mangled}(");
            emit_params(out, f.params);
            let _ = writeln!(out, ") -> {}", render_type(f.return_type));
        }
        return;
    }
    let _ = write!(out, "{prefix}fn {}(", f.name);
    emit_params(out, f.params);
    let ret = render_type(f.return_type);
    if ret == "()" {
        let _ = writeln!(out, ")");
    } else {
        let _ = writeln!(out, ") -> {ret}");
    }
}

fn emit_fn_signature_with_ret(
    out: &mut String,
    f: &FunctionDescriptor<'_>,
    ret_name: &str,
    prefix: &str,
) {
    let _ = write!(out, "{prefix}fn {}(", f.name);
    emit_params(out, f.params);
    let _ = writeln!(out, ") -> {ret_name}");
}

fn emit_params(out: &mut String, params: &[haphe::ParamDescriptor<'_>]) {
    for (i, p) in params.iter().enumerate() {
        if i > 0 {
            let _ = write!(out, ", ");
        }
        let _ = write!(out, "{}: {}", p.name, render_type(p.ty));
    }
}

fn render_type(td: &TypeDescriptor<'_>) -> String {
    match td {
        TypeDescriptor::Primitive(p) => match p {
            PrimitiveType::Bool => "bool".into(),
            PrimitiveType::I8
            | PrimitiveType::I16
            | PrimitiveType::I32
            | PrimitiveType::I64
            | PrimitiveType::I128
            | PrimitiveType::U8
            | PrimitiveType::U16
            | PrimitiveType::U32
            | PrimitiveType::U64
            | PrimitiveType::U128 => "int".into(),
            PrimitiveType::F32 | PrimitiveType::F64 => "float".into(),
            PrimitiveType::Char => "char".into(),
            _ => unreachable!("unhandled PrimitiveType variant"),
        },
        TypeDescriptor::String => "String".into(),
        TypeDescriptor::Bytes => "Blob".into(),
        TypeDescriptor::Unit => "()".into(),
        TypeDescriptor::Option(inner) => format!("{}?", render_type(inner)),
        TypeDescriptor::List(_) | TypeDescriptor::Array(_, _) => "Array".into(),
        TypeDescriptor::Map(_, _) => "Map".into(),
        TypeDescriptor::Tuple(elems) => {
            let inner: Vec<_> = elems.iter().map(render_type).collect();
            format!("({})", inner.join(", "))
        }
        TypeDescriptor::Result(ok, _) => render_type(ok),
        TypeDescriptor::Callback {
            params,
            return_type,
        } => {
            let args: Vec<_> = params.iter().map(render_type).collect();
            let ret = render_type(return_type);
            if ret == "()" {
                format!("Fn({})", args.join(", "))
            } else {
                format!("Fn({}) -> {ret}", args.join(", "))
            }
        }
        TypeDescriptor::Ref(id) => id
            .as_str()
            .rsplit("::")
            .next()
            .unwrap_or(id.as_str())
            .into(),
        TypeDescriptor::Instance { id, args } => {
            let name = id
                .as_str()
                .rsplit("::")
                .next()
                .unwrap_or(id.as_str());
            let rendered: Vec<_> = args.iter().map(render_type).collect();
            format!("{name}<{}>", rendered.join(", "))
        }
        TypeDescriptor::Borrowed { inner, .. } => render_type(inner),
        TypeDescriptor::GenericParam(name) => (*name).into(),
        TypeDescriptor::Stream(inner) => format!("Stream<{}>", render_type(inner)),
        TypeDescriptor::Future(inner) => format!("Future<{}>", render_type(inner)),
        _ => "Dynamic".into(),
    }
}

#[allow(
    clippy::match_same_arms,
    reason = "policy table: one arm per operator kind for clarity"
)]
fn collect_operators(trait_impls: &[haphe::TraitImpl<'_>]) -> Vec<&'static str> {
    let mut ops = Vec::new();
    for ti in trait_impls {
        let op = match ti {
            haphe::TraitImpl::Display => "to_string",
            haphe::TraitImpl::ToString => "+str",
            haphe::TraitImpl::Debug => "to_debug",
            haphe::TraitImpl::Hash => "hash",
            haphe::TraitImpl::PartialEq | haphe::TraitImpl::Eq => "==",
            haphe::TraitImpl::PartialOrd | haphe::TraitImpl::Ord => "<",
            haphe::TraitImpl::Clone => continue,
            haphe::TraitImpl::Default => "default",
            haphe::TraitImpl::Add { .. } => "+",
            haphe::TraitImpl::Sub { .. } => "-",
            haphe::TraitImpl::Mul { .. } => "*",
            haphe::TraitImpl::Div { .. } => "/",
            haphe::TraitImpl::Rem { .. } | haphe::TraitImpl::Mod { .. } => "%",
            haphe::TraitImpl::IDiv { .. } => continue,
            haphe::TraitImpl::Pow { .. } => "**",
            haphe::TraitImpl::Neg { .. } => "-unary",
            haphe::TraitImpl::Not { .. } => "!",
            haphe::TraitImpl::BitAnd { .. } => "&",
            haphe::TraitImpl::BitOr { .. } => "|",
            haphe::TraitImpl::BitXor { .. } => "^",
            haphe::TraitImpl::Shl { .. } => "<<",
            haphe::TraitImpl::Shr { .. } => ">>",
            haphe::TraitImpl::Call { .. } | haphe::TraitImpl::AsyncCall { .. } => "call",
            haphe::TraitImpl::Index { .. } | haphe::TraitImpl::IndexMut { .. } => "[]",
            haphe::TraitImpl::Iterator { .. } | haphe::TraitImpl::IntoIterator { .. } => "iter",
            _ => continue,
        };
        if !ops.contains(&op) {
            ops.push(op);
        }
    }
    ops
}
